// GENERATED by tools/gen_drill_lib.py from content/drills/*.yaml — do not edit.
export type Drill = {
  id: string;
  name: string;
  /** Fault ids this drill fixes (content/faults). */
  targets: string[];
  duration: string;
  equipment: string;
  protocol: string;
};

export const DRILLS: Drill[] = [
  {
    "id": "bounce_rhythm_rounds",
    "name": "Bounce rhythm rounds",
    "targets": [
      "flat_feet_under_fire"
    ],
    "duration": "3x2min",
    "equipment": "none",
    "protocol": "Metronome-guided light bounce with punch calls layered on top — the graded quantity is bounce cadence PERSISTING through the punching, not the punches. Cadence presence measured by the rhythm module per 10s window."
  },
  {
    "id": "broken_rhythm_rounds",
    "name": "Broken rhythm rounds",
    "targets": [
      "predictable_rhythm"
    ],
    "duration": "3x2min",
    "equipment": "none",
    "protocol": "App plays an irregular audio beat (deterministic per-round seed from session id) and calls tempo switches: \"double time… freeze… explode\". Scored on rhythm.predictability_index per round, target decreasing round over round."
  },
  {
    "id": "chin_tuck_rounds",
    "name": "Chin-tuck posture rounds",
    "targets": [
      "chin_up"
    ],
    "duration": "3x90s",
    "equipment": "none",
    "protocol": "Slow-tempo shadowboxing with the chin-position track graded continuously. App calls \"check\" at random intervals; user resets posture; drift rate between checks is the score."
  },
  {
    "id": "conditioning_output_intervals",
    "name": "Output intervals",
    "targets": [
      "hands_drop_after_punch"
    ],
    "duration": "6x60s (20s high output / 40s active guard)",
    "equipment": "none",
    "protocol": "Interval rounds targeting the fatigue cause of dropped hands: 20 s maximum punch output, 40 s movement with guard held. The graded quantity is guard_recovery_ms drift across intervals — the drill is passed by holding form under fatigue, not by raw punch count (quality-weighted XP, docs/09 §4)."
  },
  {
    "id": "guard_discipline_rounds",
    "name": "Guard discipline rounds",
    "targets": [
      "guard_low_at_rest"
    ],
    "duration": "3x2min",
    "equipment": "none",
    "protocol": "Normal shadowboxing but the ONLY graded quantity is guard_up_fraction from the continuous guard sampler. Live cue fires after 3 consecutive seconds below guard; end-of-round readout is the fraction plus the longest lapse."
  },
  {
    "id": "head_movement_u_drill",
    "name": "U-shape head movement drill",
    "targets": [
      "leaning_back_when_defending",
      "chin_up"
    ],
    "duration": "3x90s",
    "equipment": "none",
    "protocol": "App calls slip-left / slip-right / roll; head trajectory is graded for the U-shape (lateral + drop) versus straight-back retreat; COM must stay over the base polygon throughout."
  },
  {
    "id": "hip_snap_pivots",
    "name": "Hip snap pivot reps",
    "targets": [
      "no_hip_rotation_rear_hand",
      "arm_punching"
    ],
    "duration": "4x60s",
    "equipment": "none",
    "protocol": "Isolated rear-hand reps at half speed focusing on heel-turn → hip → shoulder sequencing. Tier-2 analysis grades kinetic-chain timing lags per rep; HFR upload recommended for the deep version."
  },
  {
    "id": "lateral_step_drills",
    "name": "Lateral step-drag drills",
    "targets": [
      "crossing_feet"
    ],
    "duration": "3x90s",
    "equipment": "none",
    "protocol": "App calls left/right movement bursts; step events are graded for step-drag order (lead foot first in direction of travel, trail foot drags) and any ankle-crossing inversion fails the rep with an immediate cue."
  },
  {
    "id": "mirror_return_high",
    "name": "Snap-back rounds",
    "targets": [
      "hands_drop_after_punch"
    ],
    "duration": "3x2min",
    "equipment": "none",
    "protocol": "App calls single shots and doubles at moderate tempo. Scoring emphasis is inverted for this drill: the punch is ungraded, the RETURN is graded. Live cue fires only on guard_recovery_ms regression; end-of-round readout is return speed, not punch speed."
  },
  {
    "id": "no_windup_wall_jabs",
    "name": "Wall jabs — no wind-up",
    "targets": [
      "telegraph_hand_dip"
    ],
    "duration": "3x2min",
    "equipment": "none",
    "protocol": "Stand in stance with your back close to a wall so a wind-up raps your knuckles: the punch must leave STRAIGHT from guard. App calls single jabs at moderate tempo; the telegraph detector grades the 300ms before each launch. Any dip below guard before firing is flagged live."
  },
  {
    "id": "prompt_double_return",
    "name": "Punish the lazy return",
    "targets": [
      "hands_drop_after_punch"
    ],
    "duration": "3x90s",
    "equipment": "none",
    "protocol": "App calls a shot; within 600ms of the user's strike apex it randomly (30%, deterministic seed) calls \"slip!\" — simulating the counter that lives in a slow return. Defensive response only counts if the guard was already recovered when the call fired. Makes the cost of the fault visceral."
  },
  {
    "id": "prompt_random_combos",
    "name": "Random combination calls",
    "targets": [
      "predictable_rhythm"
    ],
    "duration": "3x2min",
    "equipment": "none",
    "protocol": "App calls combinations from the user's known set in unpredictable order and timing (deterministic per-round seed from session id). Grades response latency and inter-strike cadence variance — the goal is breaking the fighter's fixed combo tempo, so *higher* cadence variance scores better."
  },
  {
    "id": "range_marker_jabs",
    "name": "Range discipline jabs",
    "targets": [
      "overextension"
    ],
    "duration": "3x90s",
    "equipment": "none",
    "protocol": "Calibration places a virtual range marker at 95% of the user's measured reach. App calls jabs; extension_frac is graded against the 0.90–1.00 band — over the band scores worse than under it. HFR capture if available."
  },
  {
    "id": "speed_ladder_relaxed",
    "name": "Relaxed speed ladder",
    "targets": [
      "telegraph_hand_dip"
    ],
    "duration": "4x1min",
    "equipment": "none",
    "protocol": "Four one-minute rungs at 50% → 70% → 85% → 95% intended speed, same jab each time. The point: speed comes from staying loose, not from loading up. The app compares your telegraph dip depth across rungs — if the dip grows with speed, you are trading tells for power. Target is rung 4 speed with rung 1 stillness before launch."
  },
  {
    "id": "stance_reset_steps",
    "name": "Stance reset stepping",
    "targets": [
      "stance_too_narrow",
      "hands_drop_after_punch"
    ],
    "duration": "3x2min",
    "equipment": "none",
    "protocol": "App calls step directions (forward/back/left/right/pivot) at building tempo. After every step the fighter must arrive back in their calibrated stance width band before the next call; the live stance-width track is scored continuously and the call tempo only rises while integrity holds."
  },
  {
    "id": "step_jab_sync",
    "name": "Step-jab synchronization",
    "targets": [
      "overextension",
      "stance_too_narrow"
    ],
    "duration": "3x90s",
    "equipment": "none",
    "protocol": "Teaches closing distance with the feet instead of the arm. App calls \"step-jab\" reps; scoring pairs each strike event with a lead-foot step event and grades their timing offset (foot lands as fist lands) plus extension_frac staying in band — reaching instead of stepping fails the rep."
  }
];
