#!/usr/bin/env python3
"""Generate web/lib/session/drills.gen.ts from content/drills/*.yaml.

The content library is the single source of truth for drills (docs/07);
the app ships a generated snapshot so the drill panel and coach card show
real protocols with zero runtime YAML. Re-run after editing content/ and
commit the output. CI's content job lints the YAML; the vitest suite pins
coach.ts drill ids to this snapshot.
"""
import json
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "content" / "drills"
OUT = REPO / "web" / "lib" / "session" / "drills.gen.ts"

def main() -> None:
    drills = []
    for p in sorted(SRC.glob("*.yaml")):
        d = yaml.safe_load(p.read_text())
        drills.append(
            {
                "id": d["id"],
                "name": d["name"],
                "targets": d.get("targets_faults", []),
                "duration": d.get("duration_default", ""),
                "equipment": d.get("equipment", "none"),
                "protocol": " ".join(str(d.get("protocol", "")).split()),
            }
        )
    body = json.dumps(drills, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// GENERATED by tools/gen_drill_lib.py from content/drills/*.yaml — do not edit.\n"
        "export type Drill = {\n"
        "  id: string;\n"
        "  name: string;\n"
        "  /** Fault ids this drill fixes (content/faults). */\n"
        "  targets: string[];\n"
        "  duration: string;\n"
        "  equipment: string;\n"
        "  protocol: string;\n"
        "};\n\n"
        f"export const DRILLS: Drill[] = {body};\n"
    )
    print(f"wrote {OUT.relative_to(REPO)} ({len(drills)} drills)")

if __name__ == "__main__":
    sys.exit(main())
